export interface GlobalCity {
  label: string;
  query: string;
  country: string;
  region: string;
  lat: number;
  lng: number;
}

export const POPULAR_CITIES: GlobalCity[] = [
  { label: "New York, NY", query: "New York, NY", country: "United States", region: "North America", lat: 40.7128, lng: -74.006 },
  { label: "London, UK", query: "London, UK", country: "United Kingdom", region: "Europe", lat: 51.5074, lng: -0.1278 },
  { label: "Los Angeles, CA", query: "Los Angeles, CA", country: "United States", region: "North America", lat: 34.0522, lng: -118.2437 },
  { label: "Chicago, IL", query: "Chicago, IL", country: "United States", region: "North America", lat: 41.8781, lng: -87.6298 },
  { label: "Toronto, ON", query: "Toronto, ON, Canada", country: "Canada", region: "North America", lat: 43.6532, lng: -79.3832 },
  { label: "Sydney, NSW", query: "Sydney, NSW, Australia", country: "Australia", region: "Oceania", lat: -33.8688, lng: 151.2093 },
  { label: "Dubai, UAE", query: "Dubai, UAE", country: "United Arab Emirates", region: "Middle East", lat: 25.2048, lng: 55.2708 },
  { label: "San Francisco, CA", query: "San Francisco, CA", country: "United States", region: "North America", lat: 37.7749, lng: -122.4194 },
  { label: "Miami, FL", query: "Miami, FL", country: "United States", region: "North America", lat: 25.7617, lng: -80.1918 },
  { label: "Dallas, TX", query: "Dallas, TX", country: "United States", region: "North America", lat: 32.7767, lng: -96.797 },
  { label: "Manchester, UK", query: "Manchester, UK", country: "United Kingdom", region: "Europe", lat: 53.4808, lng: -2.2426 },
  { label: "Singapore", query: "Singapore", country: "Singapore", region: "Asia", lat: 1.3521, lng: 103.8198 },
];

export const WORLDWIDE_CITIES: Record<string, GlobalCity[]> = {
  "United States": [
    { label: "New York, NY", query: "New York, NY", country: "United States", region: "North America", lat: 40.7128, lng: -74.006 },
    { label: "Los Angeles, CA", query: "Los Angeles, CA", country: "United States", region: "North America", lat: 34.0522, lng: -118.2437 },
    { label: "Chicago, IL", query: "Chicago, IL", country: "United States", region: "North America", lat: 41.8781, lng: -87.6298 },
    { label: "Houston, TX", query: "Houston, TX", country: "United States", region: "North America", lat: 29.7604, lng: -95.3698 },
    { label: "Phoenix, AZ", query: "Phoenix, AZ", country: "United States", region: "North America", lat: 33.4484, lng: -112.074 },
    { label: "Philadelphia, PA", query: "Philadelphia, PA", country: "United States", region: "North America", lat: 39.9526, lng: -75.1652 },
    { label: "San Antonio, TX", query: "San Antonio, TX", country: "United States", region: "North America", lat: 29.4241, lng: -98.4936 },
    { label: "San Diego, CA", query: "San Diego, CA", country: "United States", region: "North America", lat: 32.7157, lng: -117.1611 },
    { label: "Dallas, TX", query: "Dallas, TX", country: "United States", region: "North America", lat: 32.7767, lng: -96.797 },
    { label: "Austin, TX", query: "Austin, TX", country: "United States", region: "North America", lat: 30.2672, lng: -97.7431 },
    { label: "San Francisco, CA", query: "San Francisco, CA", country: "United States", region: "North America", lat: 37.7749, lng: -122.4194 },
    { label: "San Jose, CA", query: "San Jose, CA", country: "United States", region: "North America", lat: 37.3382, lng: -121.8863 },
    { label: "Seattle, WA", query: "Seattle, WA", country: "United States", region: "North America", lat: 47.6062, lng: -122.3321 },
    { label: "Denver, CO", query: "Denver, CO", country: "United States", region: "North America", lat: 39.7392, lng: -104.9903 },
    { label: "Washington, DC", query: "Washington, DC", country: "United States", region: "North America", lat: 38.9072, lng: -77.0369 },
    { label: "Boston, MA", query: "Boston, MA", country: "United States", region: "North America", lat: 42.3601, lng: -71.0589 },
    { label: "Nashville, TN", query: "Nashville, TN", country: "United States", region: "North America", lat: 36.1627, lng: -86.7816 },
    { label: "Atlanta, GA", query: "Atlanta, GA", country: "United States", region: "North America", lat: 33.749, lng: -84.388 },
    { label: "Miami, FL", query: "Miami, FL", country: "United States", region: "North America", lat: 25.7617, lng: -80.1918 },
    { label: "Orlando, FL", query: "Orlando, FL", country: "United States", region: "North America", lat: 28.5383, lng: -81.3792 },
    { label: "Las Vegas, NV", query: "Las Vegas, NV", country: "United States", region: "North America", lat: 36.1699, lng: -115.1398 },
    { label: "Portland, OR", query: "Portland, OR", country: "United States", region: "North America", lat: 45.5152, lng: -122.6784 },
    { label: "Charlotte, NC", query: "Charlotte, NC", country: "United States", region: "North America", lat: 35.2271, lng: -80.8431 },
    { label: "Tampa, FL", query: "Tampa, FL", country: "United States", region: "North America", lat: 27.9506, lng: -82.4572 },
    { label: "Minneapolis, MN", query: "Minneapolis, MN", country: "United States", region: "North America", lat: 44.9778, lng: -93.265 },
  ],
  "United Kingdom": [
    { label: "London", query: "London, UK", country: "United Kingdom", region: "Europe", lat: 51.5074, lng: -0.1278 },
    { label: "Manchester", query: "Manchester, UK", country: "United Kingdom", region: "Europe", lat: 53.4808, lng: -2.2426 },
    { label: "Birmingham", query: "Birmingham, UK", country: "United Kingdom", region: "Europe", lat: 52.4862, lng: -1.8904 },
    { label: "Leeds", query: "Leeds, UK", country: "United Kingdom", region: "Europe", lat: 53.8008, lng: -1.5491 },
    { label: "Glasgow", query: "Glasgow, UK", country: "United Kingdom", region: "Europe", lat: 55.8642, lng: -4.2518 },
    { label: "Edinburgh", query: "Edinburgh, UK", country: "United Kingdom", region: "Europe", lat: 55.9533, lng: -3.1883 },
    { label: "Liverpool", query: "Liverpool, UK", country: "United Kingdom", region: "Europe", lat: 53.4084, lng: -2.9916 },
    { label: "Bristol", query: "Bristol, UK", country: "United Kingdom", region: "Europe", lat: 51.4545, lng: -2.5879 },
    { label: "Newcastle", query: "Newcastle, UK", country: "United Kingdom", region: "Europe", lat: 54.9783, lng: -1.6178 },
    { label: "Sheffield", query: "Sheffield, UK", country: "United Kingdom", region: "Europe", lat: 53.3811, lng: -1.4701 },
    { label: "Belfast", query: "Belfast, UK", country: "United Kingdom", region: "Europe", lat: 54.5973, lng: -5.9301 },
    { label: "Cardiff", query: "Cardiff, UK", country: "United Kingdom", region: "Europe", lat: 51.4816, lng: -3.1791 },
  ],
  "Canada": [
    { label: "Toronto, ON", query: "Toronto, ON, Canada", country: "Canada", region: "North America", lat: 43.6532, lng: -79.3832 },
    { label: "Vancouver, BC", query: "Vancouver, BC, Canada", country: "Canada", region: "North America", lat: 49.2827, lng: -123.1207 },
    { label: "Montreal, QC", query: "Montreal, QC, Canada", country: "Canada", region: "North America", lat: 45.5017, lng: -73.5673 },
    { label: "Calgary, AB", query: "Calgary, AB, Canada", country: "Canada", region: "North America", lat: 51.0447, lng: -114.0719 },
    { label: "Ottawa, ON", query: "Ottawa, ON, Canada", country: "Canada", region: "North America", lat: 45.4215, lng: -75.6972 },
    { label: "Edmonton, AB", query: "Edmonton, AB, Canada", country: "Canada", region: "North America", lat: 53.5461, lng: -113.4938 },
    { label: "Mississauga, ON", query: "Mississauga, ON, Canada", country: "Canada", region: "North America", lat: 43.589, lng: -79.6441 },
    { label: "Winnipeg, MB", query: "Winnipeg, MB, Canada", country: "Canada", region: "North America", lat: 49.8951, lng: -97.1384 },
  ],
  "Australia & NZ": [
    { label: "Sydney, NSW", query: "Sydney, NSW, Australia", country: "Australia", region: "Oceania", lat: -33.8688, lng: 151.2093 },
    { label: "Melbourne, VIC", query: "Melbourne, VIC, Australia", country: "Australia", region: "Oceania", lat: -37.8136, lng: 144.9631 },
    { label: "Brisbane, QLD", query: "Brisbane, QLD, Australia", country: "Australia", region: "Oceania", lat: -27.4698, lng: 153.0251 },
    { label: "Perth, WA", query: "Perth, WA, Australia", country: "Australia", region: "Oceania", lat: -31.9505, lng: 115.8605 },
    { label: "Adelaide, SA", query: "Adelaide, SA, Australia", country: "Australia", region: "Oceania", lat: -34.9285, lng: 138.6007 },
    { label: "Gold Coast, QLD", query: "Gold Coast, QLD, Australia", country: "Australia", region: "Oceania", lat: -28.0167, lng: 153.4 },
    { label: "Auckland, NZ", query: "Auckland, New Zealand", country: "New Zealand", region: "Oceania", lat: -36.8485, lng: 174.7633 },
    { label: "Wellington, NZ", query: "Wellington, New Zealand", country: "New Zealand", region: "Oceania", lat: -41.2865, lng: 174.7762 },
  ],
  "Europe": [
    { label: "Paris, France", query: "Paris, France", country: "France", region: "Europe", lat: 48.8566, lng: 2.3522 },
    { label: "Berlin, Germany", query: "Berlin, Germany", country: "Germany", region: "Europe", lat: 52.52, lng: 13.405 },
    { label: "Munich, Germany", query: "Munich, Germany", country: "Germany", region: "Europe", lat: 48.1351, lng: 11.582 },
    { label: "Frankfurt, Germany", query: "Frankfurt, Germany", country: "Germany", region: "Europe", lat: 50.1109, lng: 8.6821 },
    { label: "Amsterdam, Netherlands", query: "Amsterdam, Netherlands", country: "Netherlands", region: "Europe", lat: 52.3676, lng: 4.9041 },
    { label: "Madrid, Spain", query: "Madrid, Spain", country: "Spain", region: "Europe", lat: 40.4168, lng: -3.7038 },
    { label: "Barcelona, Spain", query: "Barcelona, Spain", country: "Spain", region: "Europe", lat: 41.3879, lng: 2.1699 },
    { label: "Rome, Italy", query: "Rome, Italy", country: "Italy", region: "Europe", lat: 41.9028, lng: 12.4964 },
    { label: "Milan, Italy", query: "Milan, Italy", country: "Italy", region: "Europe", lat: 45.4642, lng: 9.19 },
    { label: "Dublin, Ireland", query: "Dublin, Ireland", country: "Ireland", region: "Europe", lat: 53.3498, lng: -6.2603 },
    { label: "Zurich, Switzerland", query: "Zurich, Switzerland", country: "Switzerland", region: "Europe", lat: 47.3769, lng: 8.5417 },
    { label: "Vienna, Austria", query: "Vienna, Austria", country: "Austria", region: "Europe", lat: 48.2082, lng: 16.3738 },
    { label: "Brussels, Belgium", query: "Brussels, Belgium", country: "Belgium", region: "Europe", lat: 50.8503, lng: 4.3517 },
    { label: "Stockholm, Sweden", query: "Stockholm, Sweden", country: "Sweden", region: "Europe", lat: 59.3293, lng: 18.0686 },
    { label: "Copenhagen, Denmark", query: "Copenhagen, Denmark", country: "Denmark", region: "Europe", lat: 55.6761, lng: 12.5683 },
    { label: "Oslo, Norway", query: "Oslo, Norway", country: "Norway", region: "Europe", lat: 59.9139, lng: 10.7522 },
  ],
  "Middle East": [
    { label: "Dubai, UAE", query: "Dubai, UAE", country: "United Arab Emirates", region: "Middle East", lat: 25.2048, lng: 55.2708 },
    { label: "Abu Dhabi, UAE", query: "Abu Dhabi, UAE", country: "United Arab Emirates", region: "Middle East", lat: 24.4539, lng: 54.3773 },
    { label: "Riyadh, Saudi Arabia", query: "Riyadh, Saudi Arabia", country: "Saudi Arabia", region: "Middle East", lat: 24.7136, lng: 46.6753 },
    { label: "Jeddah, Saudi Arabia", query: "Jeddah, Saudi Arabia", country: "Saudi Arabia", region: "Middle East", lat: 21.5433, lng: 39.1728 },
    { label: "Doha, Qatar", query: "Doha, Qatar", country: "Qatar", region: "Middle East", lat: 25.2854, lng: 51.531 },
    { label: "Kuwait City, Kuwait", query: "Kuwait City, Kuwait", country: "Kuwait", region: "Middle East", lat: 29.3759, lng: 47.9774 },
    { label: "Manama, Bahrain", query: "Manama, Bahrain", country: "Bahrain", region: "Middle East", lat: 26.2285, lng: 50.586 },
    { label: "Muscat, Oman", query: "Muscat, Oman", country: "Oman", region: "Middle East", lat: 23.5859, lng: 58.4059 },
  ],
  "Asia": [
    { label: "Singapore", query: "Singapore", country: "Singapore", region: "Asia", lat: 1.3521, lng: 103.8198 },
    { label: "Tokyo, Japan", query: "Tokyo, Japan", country: "Japan", region: "Asia", lat: 35.6762, lng: 139.6503 },
    { label: "Hong Kong", query: "Hong Kong", country: "Hong Kong", region: "Asia", lat: 22.3193, lng: 114.1694 },
    { label: "Mumbai, India", query: "Mumbai, India", country: "India", region: "Asia", lat: 19.076, lng: 72.8777 },
    { label: "Delhi, India", query: "Delhi, India", country: "India", region: "Asia", lat: 28.6139, lng: 77.209 },
    { label: "Bengaluru, India", query: "Bengaluru, India", country: "India", region: "Asia", lat: 12.9716, lng: 77.5946 },
    { label: "Hyderabad, India", query: "Hyderabad, India", country: "India", region: "Asia", lat: 17.385, lng: 78.4867 },
    { label: "Kuala Lumpur, Malaysia", query: "Kuala Lumpur, Malaysia", country: "Malaysia", region: "Asia", lat: 3.139, lng: 101.6869 },
    { label: "Bangkok, Thailand", query: "Bangkok, Thailand", country: "Thailand", region: "Asia", lat: 13.7563, lng: 100.5018 },
    { label: "Seoul, South Korea", query: "Seoul, South Korea", country: "South Korea", region: "Asia", lat: 37.5665, lng: 126.978 },
  ],
  "Latin America": [
    { label: "Sao Paulo, Brazil", query: "Sao Paulo, Brazil", country: "Brazil", region: "South America", lat: -23.5505, lng: -46.6333 },
    { label: "Rio de Janeiro, Brazil", query: "Rio de Janeiro, Brazil", country: "Brazil", region: "South America", lat: -22.9068, lng: -43.1729 },
    { label: "Mexico City, Mexico", query: "Mexico City, Mexico", country: "Mexico", region: "North America", lat: 19.4326, lng: -99.1332 },
    { label: "Buenos Aires, Argentina", query: "Buenos Aires, Argentina", country: "Argentina", region: "South America", lat: -34.6037, lng: -58.3816 },
    { label: "Bogota, Colombia", query: "Bogota, Colombia", country: "Colombia", region: "South America", lat: 4.711, lng: -74.0721 },
    { label: "Santiago, Chile", query: "Santiago, Chile", country: "Chile", region: "South America", lat: -33.4489, lng: -70.6693 },
    { label: "Lima, Peru", query: "Lima, Peru", country: "Peru", region: "South America", lat: -12.0464, lng: -77.0428 },
  ],
};
