import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowUpRight, ArrowRight, Search, Instagram, Users, Activity } from "lucide-react";
import { apiClient } from "@/lib/api-client";
interface Overview {leads:{total:number;qualified:number;closed:number;with_website:number};jobs:{id:string;kind:string;status:string;created_at:string;error?:string}[];instagram:{sent:number;needs_attention:number}}
export function OverviewPage(){
 const query=useQuery({queryKey:['overview'],queryFn:()=>apiClient.get<Overview>('/overview'),refetchInterval:30000});
 return <div className="page-wrap"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">THE BIG PICTURE</p><h1 className="page-title">Room to grow.</h1><p className="mt-3 text-sm text-muted-foreground">Your leads, conversations, and next steps. All in one place.</p></div><Link to="/discovery" className="action-primary">Discover businesses <ArrowUpRight size={17}/></Link></div>
 {query.isError?<div role="alert" className="notice mt-8">{query.error.message}<button className="ml-3 underline" onClick={()=>void query.refetch()}>Try again</button></div>:<>
 <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Businesses in pipeline',query.data?.leads.total],['Qualified opportunities',query.data?.leads.qualified],['Closed leads',query.data?.leads.closed],['Instagram messages sent',query.data?.instagram.sent]].map(([label,value])=><div className="metric-card" key={String(label)}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-5 text-4xl font-medium tracking-tight">{query.isLoading?'—':value??0}</p></div>)}</div>
 <div className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl border bg-card"><div className="flex items-center justify-between border-b p-6"><h2 className="font-semibold">Recent activity</h2><Activity size={17} className="text-muted-foreground"/></div><div className="divide-y">{query.data?.jobs.length?query.data.jobs.map(job=><div className="flex items-center gap-4 px-6 py-5" key={job.id}><div className="rounded-lg bg-muted p-2.5"><Search size={16}/></div><div className="min-w-0 flex-1"><p className="text-sm font-medium capitalize">{job.kind} job</p><p className="mt-1 truncate text-xs text-muted-foreground">{job.error??new Date(job.created_at).toLocaleString()}</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs capitalize">{job.status}</span></div>):<div className="px-6 py-16 text-center"><SproutIllustration/><p className="mt-4 text-sm font-medium">Your next chapter starts with a search.</p><p className="mt-2 text-xs text-muted-foreground">Discovery jobs and their results will appear here.</p></div>}</div></section>
 <section className="space-y-4"><div className="rounded-2xl bg-[#e8efdf] p-7 text-[#203c30]"><p className="eyebrow text-[#526849]">START WITH THE RIGHT PEOPLE</p><h2 className="mt-4 font-display text-3xl leading-tight">A business behind<br/>every record.</h2><p className="mt-4 max-w-sm text-sm leading-relaxed text-[#526849]">Find businesses through open data. Review their source, enrich their details, and decide who belongs in your pipeline.</p><Link to="/discovery" className="mt-7 flex items-center gap-2 text-sm font-semibold">Explore discovery <ArrowRight size={17}/></Link></div>{[{to:'/',icon:Users,title:'Organize your pipeline',text:'Turn promising businesses into next steps.'},{to:'/instagram',icon:Instagram,title:'Keep conversations moving',text:query.data?.instagram.needs_attention?`${query.data.instagram.needs_attention} deliveries need attention.`:'Manage replies and review delivery activity.'}].map(({to,icon:Icon,title,text})=><Link key={to} to={to} className="flex items-center gap-4 rounded-xl border bg-card p-5 transition-colors hover:bg-muted"><Icon size={20} className="text-primary"/><div className="flex-1"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{text}</p></div><ArrowUpRight size={17}/></Link>)}</section></div>
 </>}</div>;
}
function SproutIllustration(){return <div aria-hidden className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-dashed border-primary/30 bg-primary/5"><Search size={24} className="text-primary/60"/></div>;}
