import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Link } from "react-router-dom";
import { apiClient } from "@/lib/api-client";
import { authApi } from "@/api/auth";
import { placesApi } from "@/api/places";
import { ArrowUpRight, Building2, User, Shield, Plug } from "lucide-react";
type Settings={display_name:string;organization_name:string;email:string;role:string};
export function SettingsPage(){
 const qc=useQueryClient();const query=useQuery({queryKey:['settings'],queryFn:()=>apiClient.get<Settings>('/settings')});const source=useQuery({queryKey:['source-status'],queryFn:placesApi.status});
 const [name,setName]=useState<string>();const [org,setOrg]=useState<string>();const [current,setCurrent]=useState('');const [password,setPassword]=useState('');
 const save=useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>apiClient.patch(path,body),onSuccess:()=>{void qc.invalidateQueries({queryKey:['settings']});toast.success('Changes saved');},onError:(e:Error)=>toast.error(e.message)});
 const change=useMutation({mutationFn:()=>authApi.changePassword(current,password),onSuccess:()=>{setCurrent('');setPassword('');toast.success('Password updated');},onError:(e:Error)=>toast.error(e.message)});
 return <div className="page-wrap max-w-5xl"><p className="eyebrow">MAKE IT YOURS</p><h1 className="page-title">Workspace settings.</h1><p className="mt-3 text-sm text-muted-foreground">Your account, workspace, and connected services.</p>{query.isError?<div className="notice mt-8">{query.error.message}</div>:query.isLoading?<p className="mt-8" role="status">Loading settings…</p>:<div className="mt-9 space-y-5">
 <section className="rounded-xl border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><Building2 size={17}/>Organization</h2><form className="mt-5 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();save.mutate({path:'/settings/organization',body:{name:org??query.data?.organization_name}});}}><label className="min-w-0 flex-1 text-xs">Workspace name<input className="field mt-2" value={org??query.data?.organization_name??''} onChange={e=>setOrg(e.target.value)} required maxLength={120} disabled={!['owner','admin'].includes(query.data?.role??'')}/></label><button className="action-primary" disabled={save.isPending||!['owner','admin'].includes(query.data?.role??'')}>Save workspace</button></form><p className="mt-3 text-xs text-muted-foreground">Workspace changes require an owner or administrator.</p></section>
 <section className="rounded-xl border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><User size={17}/>Your profile</h2><p className="mt-2 text-sm text-muted-foreground">{query.data?.email}</p><form className="mt-5 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();save.mutate({path:'/settings/profile',body:{displayName:name??query.data?.display_name}});}}><label className="min-w-0 flex-1 text-xs">Display name<input className="field mt-2" value={name??query.data?.display_name??''} onChange={e=>setName(e.target.value)} required maxLength={120}/></label><button className="action-primary" disabled={save.isPending}>Save profile</button></form></section>
 <section className="rounded-xl border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><Plug size={17}/>Connections</h2><div className="mt-5 divide-y"><div className="py-3"><p className="text-sm font-medium">Free business discovery</p><p className="mt-2 text-xs text-muted-foreground">{source.data?.message??'Checking source…'}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">An administrator can configure an open-data extract or an endpoint permitted for this deployment. No paid Google key is required.</p></div><Link to="/instagram" className="flex items-center justify-between py-4 text-sm">Instagram connection and automation<ArrowUpRight size={17}/></Link><Link to="/outreach" className="flex items-center justify-between py-4 text-sm">Email sender identities<ArrowUpRight size={17}/></Link></div></section>
 <section className="rounded-xl border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><Shield size={17}/>Account security</h2><form onSubmit={e=>{e.preventDefault();change.mutate();}} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs">Current password<input type="password" autoComplete="current-password" className="field mt-2" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label className="text-xs">New password<input type="password" autoComplete="new-password" className="field mt-2" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label><button className="action-primary justify-self-start" disabled={change.isPending}>Update password</button></form></section>
 </div>}</div>;
}
