import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Search, ArrowUpRight, MapPin, Globe, Phone, Loader2, Check } from "lucide-react";
import { Link } from "react-router-dom";
import { placesApi, type PlacesSearchParams } from "@/api/places";
import { leadsApi } from "@/api/leads";
import { jobsApi } from "@/api/jobs";
import { apiClient } from "@/lib/api-client";
export function DiscoveryPage(){
 const [mode,setMode]=useState<'city'|'radius'>('city');const [city,setCity]=useState('');const [lat,setLat]=useState('');const [lng,setLng]=useState('');const [radius,setRadius]=useState('5000');const [category,setCategory]=useState('cafes');const [jobId,setJobId]=useState<string>();const [searched,setSearched]=useState<PlacesSearchParams>();
 const status=useQuery({queryKey:['source-status'],queryFn:placesApi.status});const categories=useQuery({queryKey:['open-categories'],queryFn:placesApi.categories});
 const search=useMutation({mutationFn:placesApi.search,onSuccess:(_data,params)=>setSearched(params)});
 const job=useQuery({queryKey:['job',jobId],queryFn:()=>jobsApi.get(jobId!),enabled:!!jobId,refetchInterval:q=>['completed','failed','cancelled'].includes(q.state.data?.job.status??'')?false:2000});
 const extract=useMutation({mutationFn:()=>leadsApi.startExtraction({...searched!,source:'openstreetmap',limit:100},crypto.randomUUID()),onSuccess:r=>setJobId(r.jobId)});
 const valid=category && (mode==='city'?city.trim().length>1:lat.trim()!==''&&lng.trim()!==''&&Number.isFinite(Number(lat))&&Math.abs(Number(lat))<=90&&Number.isFinite(Number(lng))&&Math.abs(Number(lng))<=180);
 const run=()=>{const params:PlacesSearchParams={categories:[category],region:mode==='city'?{type:'city',query:city.trim()}:{type:'radius',center:{lat:Number(lat),lng:Number(lng)},radiusMeters:Number(radius)},limit:20};setSearched(undefined);search.reset();extract.reset();search.mutate(params);};
 return <div className="page-wrap"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">DISCOVERY / OPEN BUSINESS DATA</p><h1 className="page-title">Find your next conversation.</h1><p className="mt-3 text-sm text-muted-foreground">Real places. Observed details. A source you can check.</p></div><span className="flex items-center gap-2 rounded-full border bg-card px-3 py-2 text-xs"><span className={`h-1.5 w-1.5 rounded-full ${status.data?.available?'bg-emerald-600':'bg-amber-500'}`}/>{status.data?.available?'Free source connected':'Source setup needed'}</span></div>
 {(status.isError||status.data?.available===false)&&<div className="notice mt-6">{status.error?.message??status.data?.message} <Link to="/settings" className="underline">View setup</Link></div>}
 <div className="mt-9 grid items-start gap-6 xl:grid-cols-[320px_1fr]"><form onSubmit={e=>{e.preventDefault();run();}} className="rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><Search size={17}/><h2 className="font-semibold">Define your search</h2></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Start with one category and a focused location.</p><label className="mb-2 mt-7 block text-xs font-medium" htmlFor="category">Business category</label><select id="category" className="field" value={category} onChange={e=>setCategory(e.target.value)}>{(categories.data?.categories??[]).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><div className="my-6 flex rounded-lg bg-muted p-1">{(['city','radius'] as const).map(m=><button key={m} type="button" onClick={()=>setMode(m)} className={`flex-1 rounded-md px-2 py-2 text-xs ${mode===m?'bg-card shadow-sm':''}`}>{m==='city'?'City or region':'Coordinates'}</button>)}</div>
 {mode==='city'?<><label className="mb-2 block text-xs font-medium" htmlFor="city">City, region and country</label><input id="city" className="field" value={city} onChange={e=>setCity(e.target.value)} placeholder="e.g. Brighton, England, UK" maxLength={120} required/><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">Local extracts match address terms. Remote city search needs a configured geocoder.</p></>:<><div className="grid grid-cols-2 gap-3"><label className="text-xs">Latitude<input className="field mt-2" type="number" step="any" min={-90} max={90} value={lat} onChange={e=>setLat(e.target.value)} required/></label><label className="text-xs">Longitude<input className="field mt-2" type="number" step="any" min={-180} max={180} value={lng} onChange={e=>setLng(e.target.value)} required/></label></div><label className="mt-4 block text-xs">Search radius<select className="field mt-2" value={radius} onChange={e=>setRadius(e.target.value)}>{[1000,5000,10000,25000,50000].map(n=><option key={n} value={n}>{n/1000} km</option>)}</select></label></>}
 <button className="action-primary mt-6 w-full" disabled={!valid||search.isPending||!status.data?.available}>{search.isPending?<Loader2 className="animate-spin" size={16}/>:<Search size={16}/>}Search businesses</button><div className="mt-7 border-t pt-5 text-xs leading-relaxed text-muted-foreground"><p className="flex items-center gap-2 font-medium text-foreground"><Check size={14}/>No generated leads</p><p className="mt-2">Contact details appear only when present in the source. Coverage varies by category and country.</p></div></form>
 <section className="min-w-0 rounded-2xl border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-6 py-5"><div><h2 className="font-semibold">Business results</h2><p className="mt-1 text-xs text-muted-foreground">{search.data?`${search.data.totalEstimate??search.data.places.length} available · previewing ${search.data.places.length}`:'Your next opportunity could be here.'}</p></div>{search.data?.places.length? <button className="action-primary py-2 text-xs" onClick={()=>extract.mutate()} disabled={!searched||search.isError||extract.isPending||search.isPending||!!jobId&&['queued','running'].includes(job.data?.job.status??'queued')}>Import up to 100 <ArrowUpRight size={15}/></button>:null}</div>
 {(search.isError||extract.isError)&&<div role="alert" className="notice m-5">{search.error?.message??extract.error?.message}</div>}
 {jobId&&<div className="m-5 rounded-lg border bg-muted/40 p-4 text-sm"><div className="flex flex-wrap justify-between gap-3"><span>Import: <strong>{job.data?.job.status??'queued'}</strong></span>{['queued','running'].includes(job.data?.job.status??'queued')?<button className="underline" onClick={()=>void apiClient.post(`/jobs/${jobId}/cancel`).then(()=>job.refetch())}>Cancel</button>:<Link className="underline" to="/">Open pipeline</Link>}</div>{job.data?.job.error&&<p role="alert" className="mt-2 text-destructive">{job.data.job.error}</p>}</div>}
 {search.isPending?<div role="status" className="p-16 text-center text-sm text-muted-foreground">Searching the connected source…</div>:search.data?.places.length?<div className="divide-y">{search.data.places.map(place=><article className="px-6 py-5" key={place.id}><div className="flex items-start justify-between gap-4"><div><h3 className="text-sm font-semibold">{place.name}</h3><p className="mt-1.5 flex items-start gap-1.5 text-xs text-muted-foreground"><MapPin size={13} className="shrink-0"/>{place.address||'Address not listed'}</p></div>{place.sourceUrl&&<a href={place.sourceUrl} target="_blank" rel="noreferrer" className="flex shrink-0 items-center gap-1 text-xs text-primary">Source <ArrowUpRight size={13}/></a>}</div><div className="mt-4 flex flex-wrap gap-4 text-xs text-muted-foreground">{place.website&&<a className="flex items-center gap-1.5 hover:text-primary" href={place.website} target="_blank" rel="noreferrer"><Globe size={13}/>Website</a>}{place.phone&&<span className="flex items-center gap-1.5"><Phone size={13}/>{place.phone}</span>}<span className="ml-auto text-[10px]">{place.attribution}</span></div></article>)}</div>:<div className="px-6 py-24 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-dashed bg-muted/50"><Globe size={30} className="text-primary/50"/></div><h3 className="mt-6 font-display text-2xl">{search.data?'No businesses found in this search.':'Start somewhere specific.'}</h3><p className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-muted-foreground">{search.data?'Try another category or a wider area. We never fill empty results with invented businesses.':'Choose a business category and location to explore your connected open-data source.'}</p></div>}
 {search.data?.nextPageToken&&<button className="m-5 rounded-lg border px-4 py-2 text-sm" disabled={search.isPending} onClick={()=>search.mutate({...searched!,pageToken:search.data!.nextPageToken!})}>Next results</button>}</section></div></div>;
}
